### ISSUE TITLE
spark-kernel can not run on ppc64 platform

### ISSUE THREAD

**Issue by xq2005** [ibm-et/spark-kernel#114]
when starting spark-kernel on ppc64 redhat6.4, always meet the following exception:

[root@sys02 ~]# uname -a
Linux sys02 2.6.32-358.el6.ppc64 #1 SMP Tue Jan 29 11:43:27 EST 2013 ppc64 ppc64 ppc64 GNU/Linux
[root@sys02 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.4 (Santiago)

15/06/24 18:44:35 INFO SparkKernel$$anon$1: Connection Profile: {
  "stdin_port" : 48177,
  "control_port" : 49058,
  "hb_port" : 60945,
  "shell_port" : 52581,
  "iopub_port" : 44264,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : "c09655a7-4811-41ce-b80e-504ab6446dce"
}
15/06/24 18:44:35 INFO SparkKernel$$anon$1: Constructing interpreter with 4 threads and with arguments:
15/06/24 18:44:35 ERROR OneForOneStrategy: exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.UnsatisfiedLinkError: jnidispatch (/com/sun/jna/linux-ppc64/libjnidispatch.so) not found in resource path
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:568)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:550)
        at com.sun.jna.Native.<clinit>(Native.java:87)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
        at org.zeromq.ZMQ.<clinit>(ZMQ.java:32)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at akka.zeromq.ZeroMQExtension$.<init>(ZeroMQExtension.scala:38)
        at akka.zeromq.ZeroMQExtension$.<clinit>(ZeroMQExtension.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Heartbeat(SocketFactory.scala:51)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Heartbeat.<init>(Heartbeat.scala:30)
        ... 18 more
15/06/24 18:44:35 ERROR OneForOneStrategy: exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: akka.zeromq.ZeroMQExtension$ (initialization failure)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:175)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.IOPub(SocketFactory.scala:86)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.IOPub.<init>(IOPub.scala:35)
        ... 18 more
Caused by: java.lang.UnsatisfiedLinkError: jnidispatch (/com/sun/jna/linux-ppc64/libjnidispatch.so) not found in resource path
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:568)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:550)
        at com.sun.jna.Native.<clinit>(Native.java:87)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
        at org.zeromq.ZMQ.<clinit>(ZMQ.java:32)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at akka.zeromq.ZeroMQExtension$.<init>(ZeroMQExtension.scala:38)
        at akka.zeromq.ZeroMQExtension$.<clinit>(ZeroMQExtension.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Heartbeat(SocketFactory.scala:51)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Heartbeat.<init>(Heartbeat.scala:30)
        ... 18 more
15/06/24 18:44:35 ERROR OneForOneStrategy: exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: akka.zeromq.ZeroMQExtension$ (initialization failure)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:175)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Stdin(SocketFactory.scala:75)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Stdin$$anonfun$$init$$1.apply(Stdin.scala:30)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Stdin$$anonfun$$init$$1.apply(Stdin.scala:30)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.ZeromqKernelMessageSocket.<init>(ZeromqKernelMessageSocket.scala:40)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Stdin.<init>(Stdin.scala:28)
        ... 18 more
Caused by: java.lang.UnsatisfiedLinkError: jnidispatch (/com/sun/jna/linux-ppc64/libjnidispatch.so) not found in resource path
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:568)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:550)
        at com.sun.jna.Native.<clinit>(Native.java:87)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
        at org.zeromq.ZMQ.<clinit>(ZMQ.java:32)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at akka.zeromq.ZeroMQExtension$.<init>(ZeroMQExtension.scala:38)
        at akka.zeromq.ZeroMQExtension$.<clinit>(ZeroMQExtension.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Heartbeat(SocketFactory.scala:51)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Heartbeat.<init>(Heartbeat.scala:30)
        ... 18 more
15/06/24 18:44:35 ERROR OneForOneStrategy: exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: akka.zeromq.ZeroMQExtension$ (initialization failure)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:175)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Shell(SocketFactory.scala:63)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Shell$$anonfun$$init$$1.apply(Shell.scala:30)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Shell$$anonfun$$init$$1.apply(Shell.scala:30)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.ZeromqKernelMessageSocket.<init>(ZeromqKernelMessageSocket.scala:40)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Shell.<init>(Shell.scala:28)
        ... 18 more
Caused by: java.lang.UnsatisfiedLinkError: jnidispatch (/com/sun/jna/linux-ppc64/libjnidispatch.so) not found in resource path
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:568)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:550)
        at com.sun.jna.Native.<clinit>(Native.java:87)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
        at org.zeromq.ZMQ.<clinit>(ZMQ.java:32)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at akka.zeromq.ZeroMQExtension$.<init>(ZeroMQExtension.scala:38)
        at akka.zeromq.ZeroMQExtension$.<clinit>(ZeroMQExtension.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Heartbeat(SocketFactory.scala:51)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Heartbeat.<init>(Heartbeat.scala:30)

**Comment by xq2005** [comment]
downloaded jna-3.4.0.jar to replace the jna-3.0.9.jar that downloaded by sbt. and start spark-kernel,
met the following problem. Any suggestion?

15/06/24 18:06:27 INFO SparkKernel$$anon$1: Connection Profile: {
  "stdin_port" : 44047,
  "control_port" : 47905,
  "hb_port" : 50132,
  "shell_port" : 41422,
  "iopub_port" : 38349,
  "ip" : "127.0.0.1",
  "transport" : "tcp",
  "signature_scheme" : "hmac-sha256",
  "key" : "f6e4cd2f-7251-4fa5-a827-9ba3a771705a"
}
15/06/24 18:06:27 INFO SparkKernel$$anon$1: Constructing interpreter with 4 threads and with arguments:
15/06/24 18:06:27 ERROR OneForOneStrategy: exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'zmq': libsodium.so.4: cannot open shared object file: No such file or directory
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
        at com.sun.jna.Library$Handler.<init>(Library.java:140)
        at com.sun.jna.Native.loadLibrary(Native.java:368)
        at com.sun.jna.Native.loadLibrary(Native.java:353)
        at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
        at org.zeromq.ZMQ.<clinit>(ZMQ.java:32)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at akka.zeromq.ZeroMQExtension$.<init>(ZeroMQExtension.scala:38)
        at akka.zeromq.ZeroMQExtension$.<clinit>(ZeroMQExtension.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Heartbeat(SocketFactory.scala:51)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Heartbeat.<init>(Heartbeat.scala:30)
        ... 18 more
15/06/24 18:06:27 ERROR OneForOneStrategy: exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: akka.zeromq.ZeroMQExtension$ (initialization failure)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:175)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Shell(SocketFactory.scala:63)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Shell$$anonfun$$init$$1.apply(Shell.scala:30)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Shell$$anonfun$$init$$1.apply(Shell.scala:30)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.ZeromqKernelMessageSocket.<init>(ZeromqKernelMessageSocket.scala:40)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Shell.<init>(Shell.scala:28)
        ... 18 more
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'zmq': libsodium.so.4: cannot open shared object file: No such file or directory
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
        at com.sun.jna.Library$Handler.<init>(Library.java:140)
        at com.sun.jna.Native.loadLibrary(Native.java:368)
        at com.sun.jna.Native.loadLibrary(Native.java:353)
        at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
        at org.zeromq.ZMQ.<clinit>(ZMQ.java:32)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at akka.zeromq.ZeroMQExtension$.<init>(ZeroMQExtension.scala:38)
        at akka.zeromq.ZeroMQExtension$.<clinit>(ZeroMQExtension.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Heartbeat(SocketFactory.scala:51)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Heartbeat.<init>(Heartbeat.scala:30)
        ... 18 more
15/06/24 18:06:27 ERROR OneForOneStrategy: exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: akka.zeromq.ZeroMQExtension$ (initialization failure)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:175)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.IOPub(SocketFactory.scala:86)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.IOPub.<init>(IOPub.scala:35)
        ... 18 more
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'zmq': libsodium.so.4: cannot open shared object file: No such file or directory
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
        at com.sun.jna.Library$Handler.<init>(Library.java:140)
        at com.sun.jna.Native.loadLibrary(Native.java:368)
        at com.sun.jna.Native.loadLibrary(Native.java:353)
        at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
        at org.zeromq.ZMQ.<clinit>(ZMQ.java:32)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at akka.zeromq.ZeroMQExtension$.<init>(ZeroMQExtension.scala:38)
        at akka.zeromq.ZeroMQExtension$.<clinit>(ZeroMQExtension.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Heartbeat(SocketFactory.scala:51)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Heartbeat.<init>(Heartbeat.scala:30)
        ... 18 more
15/06/24 18:06:27 ERROR OneForOneStrategy: exception during creation
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
        at akka.util.Reflect$.instantiate(Reflect.scala:66)
        at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
        at akka.actor.Props.newActor(Props.scala:252)
        at akka.actor.ActorCell.newActor(ActorCell.scala:552)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: akka.zeromq.ZeroMQExtension$ (initialization failure)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:175)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Stdin(SocketFactory.scala:75)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Stdin$$anonfun$$init$$1.apply(Stdin.scala:30)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Stdin$$anonfun$$init$$1.apply(Stdin.scala:30)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.ZeromqKernelMessageSocket.<init>(ZeromqKernelMessageSocket.scala:40)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Stdin.<init>(Stdin.scala:28)
        ... 18 more
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'zmq': libsodium.so.4: cannot open shared object file: No such file or directory
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
        at com.sun.jna.Library$Handler.<init>(Library.java:140)
        at com.sun.jna.Native.loadLibrary(Native.java:368)
        at com.sun.jna.Native.loadLibrary(Native.java:353)
        at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
        at org.zeromq.ZMQ.<clinit>(ZMQ.java:32)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at akka.zeromq.ZeroMQExtension$.<init>(ZeroMQExtension.scala:38)
        at akka.zeromq.ZeroMQExtension$.<clinit>(ZeroMQExtension.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.SocketFactory.Heartbeat(SocketFactory.scala:51)
        at com.ibm.spark.kernel.protocol.v5.kernel.socket.Heartbeat.<init>(Heartbeat.scala:30)

**Comment by rcsenkbeil** [comment]
I'm seeing the old `akka.zeromq` package in your stack trace:

<pre>
Caused by: java.lang.UnsatisfiedLinkError: jnidispatch (/com/sun/jna/linux-ppc64/libjnidispatch.so) not found in resource path
at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:568)
at com.sun.jna.Native.loadNativeLibrary(Native.java:550)
at com.sun.jna.Native.(Native.java:87)
at java.lang.J9VMInternals.initializeImpl(Native Method)
at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
at org.zeromq.ZeroMQ$.loadLibrary(ZeroMQLibrary.scala:97)
<b>at org.zeromq.ZMQ.(ZMQ.java:32)</b>
at java.lang.J9VMInternals.initializeImpl(Native Method)
at java.lang.J9VMInternals.initialize(J9VMInternals.java:235)
at akka.zeromq.ZeroMQExtension$.(ZeroMQExtension.scala:38)
</pre>

This dependency should have been removed as of [this tagged commit](https://github.com/ibm-et/spark-kernel/releases/tag/v0.1.2-jeromq). Do you have the latest code as of yesterday? If so, you should no longer have a JNI dependency on libzmq.

**Comment by xq2005** [comment]
the new release can fix this problem
