### ISSUE TITLE
Spark 1.5.0 compatibility issue

### ISSUE THREAD

**Issue by ReeceRobinson** [ibm-et/spark-kernel#133]
I have been using this spark-kernel successfully with Jupyter v4 and  spark 1.4.1. I just upgraded spark to 1.5.0 and I get the following error when the kernel tries to initialise:

15/09/14 01:35:31 [ERROR] a.a.ActorSystemImpl - Uncaught fatal error from thread [sparkDriver-akka.remote.default-remote-dispatcher-7] shutting down ActorSystem [sparkDriver]
java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: createWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in function
	at akka.remote.transport.netty.NettyTransport.<init>(NettyTransport.scala:283)
	at akka.remote.transport.netty.NettyTransport.<init>(NettyTransport.scala:240)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
	at scala.util.Try$.apply(Try.scala:161)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	at scala.util.Success.flatMap(Try.scala:200)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
	at akka.remote.EndpointManager$$anonfun$9.apply(Remoting.scala:711)
	at akka.remote.EndpointManager$$anonfun$9.apply(Remoting.scala:703)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
	at akka.remote.EndpointManager.akka$remote$EndpointManager$$listens(Remoting.scala:703)
	at akka.remote.EndpointManager$$anonfun$receive$2.applyOrElse(Remoting.scala:491)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.remote.EndpointManager.aroundReceive(Remoting.scala:394)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
15/09/14 01:35:31 [ERROR] Remoting - Remoting system has been terminated abrubtly. Attempting to shut down transports
[W 01:35:37.195 NotebookApp] Timeout waiting for kernel_info reply from 1902bc96-e1b9-4b1d-8830-2735d192926b
15/09/14 01:35:37 [INFO] c.i.s.k.p.v.r.KernelMessageRelay - Not ready for messages! Stashing until ready!
15/09/14 01:35:41 [ERROR] o.a.s.SparkContext - Error initializing SparkContext.

Has anyone else had this issue? Any ideas on a workaround/fix?

Cheers,
Reece

**Comment by lbustelo** [comment]
Did you try rebuilding the kernel pointed to spark 1.5?

Gino B.

**Comment by ReeceRobinson** [comment]
I didn't. To do this do I change the project/Common.scala file and update defaultSparkVersion? ie.

val defaultSparkVersion = "1.5.0"

**Comment by pdendek** [comment]
I went through the build procedure both ways
1. by changing project/Common.scala deps and in the next shot
2. by passing Spark version with commandline like the following:
`APACHE_SPARK_VERSION=1.5.0 sbt clean compile`
`APACHE_SPARK_VERSION=1.5.0 sbt pack`

After running:
`IPYTHON_OPTS=notebook pyspark`
I got the result as @ReeceRobinson showed previously, i.e.:
(...)
15/09/14 10:42:35 [INFO] Remoting - Starting remoting
15/09/14 10:42:35 [ERROR] a.a.ActorSystemImpl - Uncaught fatal error from thread [sparkDriver-akka.remote.default-remote-dispatcher-8] shutting down ActorSystem [sparkDriver]
java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: createWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in function 
        at akka.remote.transport.netty.NettyTransport.<init>(NettyTransport.scala:283)
        at akka.remote.transport.netty.NettyTransport.<init>(NettyTransport.scala:240)
(...)

could you provide branches for versions of Spark since 1.3 ?
That would make easier building appropriate kernel 
(and make all maintenance more painful, I guess...)

**Comment by rcsenkbeil** [comment]
From a quick glance, this appears to be an issue with a version of netty being brought in.
<img width="504" alt="screen shot 2015-09-14 at 11 45 16 am" src="https://cloud.githubusercontent.com/assets/2481802/9855799/31deae7e-5ad6-11e5-8900-5c1fb82c4035.png">

Renaming or removing the netty 3.2.2 dependency results in a working kernel for me both with local and standalone modes.
<img width="566" alt="screen shot 2015-09-14 at 11 45 50 am" src="https://cloud.githubusercontent.com/assets/2481802/9855815/454dda34-5ad6-11e5-95b3-a3670622b8cf.png">

@lbustelo, @Lull3rSkat3r I can't find where netty 3.2.2 is brought in on the main configuration. Checking the test configuration via `APACHE_SPARK_VERSION=1.5.0 sbt test:dependencyTree` yields the following:
<img width="571" alt="screen shot 2015-09-14 at 11 47 19 am" src="https://cloud.githubusercontent.com/assets/2481802/9855852/87949504-5ad6-11e5-875c-563fa53b1df7.png">

Following the trace makes it appear as if `org.apache.spark:spark-core_2.10:1.5.0 [S]` is the culprit, but that doesn't make sense (otherwise everyone would have this issue). Dependencies need to be investigated for Spark 1.5.0. Furthermore, might not be a bad idea for separate branches for Spark versions.

**Comment by rcsenkbeil** [comment]
@ReeceRobinson, @pdendek, could you try out this branch? https://github.com/ibm-et/spark-kernel/tree/FixSparkDependencies1.5.x It excludes the old netty from spark core and updates the akka version to 2.3.11. It's worked for me with local and standalone.

**Comment by pdendek** [comment]
@rcsenkbeil The new branch works for me (tested in the local mode).
Thanks for your fast reply!

**Comment by ReeceRobinson** [comment]
The new branch works for me too. Thanks for your help!

**Comment by rcsenkbeil** [comment]
The master branch is now using Apache Spark 1.5.0 with fixes. New branches have been created for Apache Spark 1.3.1 and 1.4.1. See the README for more information.
