### ISSUE TITLE
sc.addJar does not add JAR

### ISSUE THREAD

**Issue by pdendek** [ibm-et/spark-kernel#134]
A quick test:
sc.addJar("/home/joe/myjar.jar")
sc.jars
>> List()

This issue has been observed with Spark 1.5.0 on Ubuntu 14.04. with spark-kernel
Adding JAR files from a notebook is a crucial feature in many applications
(esp. of my own)

Looking forward for the feedback.

**Comment by rcsenkbeil** [comment]
Have you tested the added jar? IIRC, sc.jars only reflects jars added via the Spark configuration.

You can see that the function returns _jars here: https://github.com/apache/spark/blob/branch-1.5/core/src/main/scala/org/apache/spark/SparkContext.scala#L251

And the addJar function only updates an http file server with the jar such that it can be served to the cluster: https://github.com/apache/spark/blob/branch-1.5/core/src/main/scala/org/apache/spark/SparkContext.scala#L1610

**Comment by pdendek** [comment]
Yes, I've tested if the file has been added, but apparently it is not loaded
> Name: Compile Error
> Message: <console>:14: error: not found: value pl
>       import my.package._
>              ^
> StackTrace: 


When I tried to sort adding JARs out in a different way
I took the approach to stop the "main" context (sc)
and create the new one (sCtx; the one that would allow me to add JAR to the config object
and eventually to SparkContext). However I get errors which doesn't occur 
when using the "main" context (sc).
The code is as follows:
```scala
import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.SparkConf
sc.stop
val conf = new SparkConf(true)
val sCtx = new SparkContext("local[4]", "test", conf)

val BASE_DIR = "/home/pdendek/"
val rawIris = (sCtx
               .textFile(BASE_DIR + "sample_data/iris.csv")
               .filter(! _.trim.isEmpty)
               .map(_.split(","))
               .map(p => (p(4), p.take(4).map(_.toDouble))))
import org.apache.spark.mllib.linalg.Vectors
import org.apache.spark.mllib.regression.LabeledPoint
val names = rawIris.map(_._1).distinct.zipWithIndex.collectAsMap
val bcNames = sc.broadcast(names)
val lp = rawIris.map(r => LabeledPoint(bcNames.value(r._1),Vectors.dense(r._2)))
```

With the StackTrace as follows:

```
bcNames: org.apache.spark.broadcast.Broadcast[scala.collection.Map[String,Long]] = Broadcast(4)
org.apache.spark.SparkException: Task not serializable
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:304)
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:294)
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2021)
        at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:314)
        at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:313)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
        at org.apache.spark.rdd.RDD.map(RDD.scala:313)
        at $iwC$$iwC$$iwC$$iwC.<init>(<console>:26)
        at $iwC$$iwC$$iwC.<init>(<console>:31)
        at $iwC$$iwC.<init>(<console>:33)
        at $iwC.<init>(<console>:35)
        at <init>(<console>:37)
        at .<init>(<console>:41)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.repl.SparkIMain$ReadEvalPrint.call(SparkIMain.scala:1065)
        at org.apache.spark.repl.SparkIMain$Request.loadAndRun(SparkIMain.scala:1340)
        at org.apache.spark.repl.SparkIMain.loadAndRunReq$1(SparkIMain.scala:840)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:871)
        at org.apache.spark.repl.SparkIMain.interpret(SparkIMain.scala:819)
        at com.ibm.spark.interpreter.ScalaInterpreter$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreter.scala:296)
        at com.ibm.spark.interpreter.ScalaInterpreter$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreter.scala:291)
        at com.ibm.spark.global.StreamState$.withStreams(StreamState.scala:80)
        at com.ibm.spark.interpreter.ScalaInterpreter$$anonfun$interpretAddTask$1.apply(ScalaInterpreter.scala:290)
        at com.ibm.spark.interpreter.ScalaInterpreter$$anonfun$interpretAddTask$1.apply(ScalaInterpreter.scala:290)
        at com.ibm.spark.utils.TaskManager$$anonfun$add$2$$anon$1.run(TaskManager.scala:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: org.apache.spark.SparkContext
Serialization stack:
        - object not serializable (class: org.apache.spark.SparkContext, value: org.apache.spark.SparkContext@18bb1b88)
        - field (class: $iwC$$iwC$$iwC$$iwC, name: mSc, type: class org.apache.spark.SparkContext)
        - object (class $iwC$$iwC$$iwC$$iwC, $iwC$$iwC$$iwC$$iwC@79e54d90)
        - field (class: $iwC$$iwC$$iwC, name: $iw, type: class $iwC$$iwC$$iwC$$iwC)
        - object (class $iwC$$iwC$$iwC, $iwC$$iwC$$iwC@7da382c2)
        - field (class: $iwC$$iwC, name: $iw, type: class $iwC$$iwC$$iwC)
        - object (class $iwC$$iwC, $iwC$$iwC@4b22a10e)
        - field (class: $iwC, name: $iw, type: class $iwC$$iwC)
        - object (class $iwC, $iwC@6cf94088)
        - field (class: $line10.$read, name: $iw, type: class $iwC)
        - object (class $line10.$read, $line10.$read@3df83828)
        - field (class: $iwC$$iwC$$iwC, name: $VAL24, type: class $line10.$read)
        - object (class $iwC$$iwC$$iwC, $iwC$$iwC$$iwC@3ba027c)
```
Is it entirely impossible to create a new SparkContext in a notebook using spark-kernel?
I hope it is solvable.

**Comment by rcsenkbeil** [comment]
Wait, are you trying to use the added jar from within the driver (kernel)? Using the Spark context to add the jar results in it being available for closures shipped over to the cluster (functions in map, reduce, etc), but not on the driver program.

`:cp my.jar` in the Spark Shell is actually using code that we contributed to enable adding the jar dynamically to the interpreter. The equivalent in the kernel is `%addjar file:my.jar`. To avoid caching, you can use `%addjar -f file:my.jar`. Both can be done via `kernel.magics.addJar("file:my.jar")`. See [this wiki page](https://github.com/ibm-et/spark-kernel/wiki/List-of-Current-Magics-for-the-Spark-Kernel) for more information on magics in the Spark Kernel.

The add jar magic takes a Java URL in string form, so you have to prepend with `file:` for a local file or `http:` for a remote file.

As for creating a new Spark Context, there is a half-finished implementation in one of our branches, but nothing is supported to allow you to restart or create your own Spark Context. Any options you want to provide need to be given when starting the Spark Kernel. See [this issue](https://github.com/ibm-et/spark-kernel/issues/70#issuecomment-73825816) for an example of adding various configurations when starting.

**Comment by rcsenkbeil** [comment]
FYI, you also need to be careful with what you create in the global namespace of the interpreter. The Spark Kernel creates a Spark Context marked as transient (as does the Spark Shell). Even though you can't fully create a new Spark Context, you would want to create one via `@transient val sCtx = new SparkContext("local[4]", "test", conf)`.

**Comment by pdendek** [comment]
@rcsenkbeil thanks for pointing to the `%addjar` magic,
it fully covers my usecase.

(Also thanks for the `@transient` tips)
