### ISSUE TITLE
Error messages on startup with the ipython repl

### ISSUE THREAD

**Issue by sbromberger** [ibm-et/spark-kernel#236]
Hi,

I'm new to both spark and spark-kernel so please forgive me if these are known/insignificant issues.

I'm running `ipython console --kernel spark` and receive the following output (I've suppressed INFO messages):

```
Starting Spark Kernel with SPARK_HOME=/usr/local/Cellar/apache-spark/1.5.2
Jupyter Console 4.0.3

[ZMQTerminalIPythonApp] Loading IPython extension: storemagic
15/12/21 19:54:56 [ERROR] c.i.s.c.s.ZeroMQSocketRunnable - Failed to retrieve next incoming message!
java.lang.IllegalStateException: Cannot receive another request
	at zmq.Rep.xrecv(Rep.java:77)
	at zmq.SocketBase.recv(SocketBase.java:679)
	at org.zeromq.ZMQ$Socket.recv(ZMQ.java:1247)
	at org.zeromq.ZFrame.recv(ZFrame.java:326)
	at org.zeromq.ZFrame.recvFrame(ZFrame.java:359)
	at org.zeromq.ZMsg.recvMsg(ZMsg.java:223)
	at com.ibm.spark.communication.socket.ZeroMQSocketRunnable.processNextInboundMessage(ZeroMQSocketRunnable.scala:121)
	at com.ibm.spark.communication.socket.ZeroMQSocketRunnable$$anonfun$run$2.apply$mcV$sp(ZeroMQSocketRunnable.scala:149)
	at com.ibm.spark.communication.socket.ZeroMQSocketRunnable$$anonfun$run$2.apply(ZeroMQSocketRunnable.scala:149)
	at com.ibm.spark.communication.socket.ZeroMQSocketRunnable$$anonfun$run$2.apply(ZeroMQSocketRunnable.scala:149)
	at scala.util.Try$.apply(Try.scala:161)
	at com.ibm.spark.communication.socket.ZeroMQSocketRunnable.run(ZeroMQSocketRunnable.scala:149)
	at java.lang.Thread.run(Thread.java:745)
15/12/21 19:54:56 [WARN] c.i.s.SparkKernel$$anon$1 - No external magics provided to MagicLoader!
15/12/21 19:54:57 [WARN] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/12/21 19:55:01 [WARN] c.i.s.k.a.Kernel - Locked to Scala interpreter with SparkIMain until decoupled!
15/12/21 19:55:01 [WARN] c.i.s.k.a.Kernel - Unable to control initialization of REPL class server!
15/12/21 19:55:01 [WARN] o.a.s.m.MetricsSystem - Using default name DAGScheduler for source because spark.app.id is not set.
15/12/21 19:55:07 [WARN] o.a.h.h.m.ObjectStore - Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
15/12/21 19:55:07 [WARN] o.a.h.h.m.ObjectStore - Failed to get database default, returning NoSuchObjectException
15/12/21 19:55:10 [WARN] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [1]:   // and at this point things APPEAR to be working normally...
```

In particular, the zmq error message at the top is a bit perplexing. I'm not worried about the hadoop errors since I don't have that installed.

Environment is OSX 10.11.2 with homebrew installs of spark, scala, zeromq. Jupyter/ipython installed via pip.

Thanks for any advice/help.

**Comment by chipsenkbeil** [comment]
Based on your log, are you saying that the kernel still works, but you are just seeing that ZMQ message? I've only heard of this happening on Windows. We might need to add more logging around that area to figure out what's going on. I haven't used Jupyter 4.x yet, but I've heard of others that have without any issues.

**Comment by sbromberger** [comment]
Yes. The error occurs but the repl appears to work. I haven't done a whole lot of testing but am happy to try anything you'd recommend.

**Comment by chipsenkbeil** [comment]
Not sure how we want to progress on this one. @lbustelo, thoughts?

**Comment by sbromberger** [comment]
Hi, just following up. Any ideas?

**Comment by lbustelo** [comment]
Someone else is posting the same exception on #239.

**Comment by justmytwospence** [comment]
I am experiencing the same issue.
