### ISSUE TITLE
Exception caused by joptsimple.OptionParser.allowsUnrecognizedOptions

### ISSUE THREAD

**Issue by esafak** [ibm-et/spark-kernel#244]
When I run spark-kernel I keep getting the following:

```java
Starting Spark Kernel with SPARK_HOME=/usr/lib/spark
Exception in thread "main" java.lang.NoSuchMethodError: joptsimple.OptionParser.allowsUnrecognizedOptions()V
	at com.ibm.spark.boot.CommandLineOptions.<init>(CommandLineOptions.scala:30)
	at com.ibm.spark.SparkKernel$delayedInit$body.apply(SparkKernel.scala:24)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at com.ibm.spark.SparkKernel$.main(SparkKernel.scala:23)
	at com.ibm.spark.SparkKernel.main(SparkKernel.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I had to modify the Makefile before it would run on my system (Ubuntu 14.04). I am using Spark 1.5.1 and Scala 2.11.1

**Comment by chipsenkbeil** [comment]
Well, we don't support Scala 2.11 yet. I believe @jodersky is tackling that problem. This implies that there is some incompatibility with the version of joptsimple being brought in since the API changed to not have allowsUnrecognizedOptions.

The library gets brought in here: https://github.com/ibm-et/spark-kernel/blob/ecfa5dd2abe8f992e54b12f4c5e411855b72e898/kernel-api/build.sbt#L44

The version we bring in hasn't changed in a long time _and_ it's the same for Scala 2.10/2.11 since it's a Java jar; so, I'm not sure what the problem might be. @lbustelo, assembly wouldn't be causing any problems, I'm assuming. Do any other dependencies bring it in? @jodersky, have you seen anything like this while working on Scala 2.11 support?

**Comment by esafak** [comment]
The same thing happens with 2.10.6, which I installed from the deb, so I must be doing something wrong. `make test` returns

```make
...
[error] Error during tests:
[error] 	system.SuiteForSystem
...
[info] Total number of tests run: 113
[info] Suites: completed 15, aborted 0
[info] Tests: succeeded 113, failed 0, canceled 0, ignored 3, pending 0
[info] All tests passed.
[error] (kernel/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 81 s, completed Jan 8, 2016 11:13:15 AM
make: *** [test] Error 1
```

**Comment by d2207197** [comment]
try add `--driver-class-path`  in `bin/spark-kernel`
```bash
exec "$SPARK_HOME"/bin/spark-submit \
  ${SPARK_OPTS} \
  --driver-class-path $PROG_HOME/lib/${KERNEL_ASSEMBLY} \
  --class com.ibm.spark.SparkKernel $PROG_HOME/lib/${KERNEL_ASSEMBLY} "$@"```
