### ISSUE TITLE
Kernel error

### ISSUE THREAD

**Issue by jtfogarty** [ibm-et/spark-kernel#99]
Hi This is Jeff Fogarty from US Bank

I'm getting the below error on my Mac;

My install is using Jupyter with Spark 1.2.1 (Scala 2.10.4) 

Can I get this to run with Jupyter?

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 365, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/handlers.py", line 53, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "/usr/local/lib/python2.7/site-packages/IPython/html/services/kernels/kernelmanager.py", line 84, in start_kernel
    kernel_name=kernel_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/kernel/multikernelmanager.py", line 112, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/IPython/kernel/manager.py", line 240, in start_kernel
    **kw)
  File "/usr/local/lib/python2.7/site-packages/IPython/kernel/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python2.7/site-packages/IPython/kernel/launcher.py", line 213, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by rcsenkbeil** [comment]
This indicates that you do not have the kernel executable on the path you specified in your kernel.json file, hence the "No such file or directory" error during the start_kernel process.

So, I'm assuming your kernel.json file for the Spark Kernel looks something like this:

```
{
    "display_name": "Spark 1.2.1 (Scala 2.10.4)",
    "language": "scala",
    "argv": [
        "/Users/MyAccount/local/bin/sparkkernel",
        "--profile",
        "{connection_file}"
     ],
     "codemirror_mode": "scala"
}
```

Make sure that you have followed the steps here: https://github.com/ibm-et/spark-kernel/wiki/Getting-Started-with-the-Spark-Kernel#getting-the-spark-kernel-running

To reiterate, you need to do the following:

1. Build the kernel: `sbt compile` from the root of the project.

2. Pack the kernel: `sbt pack` from the root of the project.

3. Move to the pack directory: `cd kernel/target/pack` from the root of the project.

4. Install the packed kernel: `make install` from _kernel/target/pack_.

This _should_ place an executable at the location `$HOME/local/bin/sparkkernel` where _$HOME_ is your home directory (something like `/Users/MyUsername` on Mac OS X).

**Comment by jtfogarty** [comment]
Looks like I just had a typo in the kernel.json
Thanks

**Comment by rcsenkbeil** [comment]
Closing this out since it appears to be resolved. Feel free to open up another issue if you encounter a different problem.
